/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DentistProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'specialty' : IDL.Text,
  'isVerified' : IDL.Bool,
  'licenseNumber' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'bookingId' : IDL.Nat,
  'messageId' : IDL.Nat,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const ToothStatus = IDL.Variant({
  'risk' : IDL.Null,
  'healthy' : IDL.Null,
  'cavity' : IDL.Null,
});
export const ToothRecord = IDL.Record({
  'status' : ToothStatus,
  'number' : IDL.Nat,
  'recommendation' : IDL.Text,
  'condition' : IDL.Text,
});
export const ScanResult = IDL.Record({
  'teeth' : IDL.Vec(ToothRecord),
  'overallScore' : IDL.Nat,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
  'declined' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'released' : IDL.Null,
});
export const Booking = IDL.Record({
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'bookingId' : IDL.Nat,
  'patientId' : IDL.Principal,
  'createdAt' : Time,
  'slotId' : IDL.Nat,
  'dentistId' : IDL.Principal,
});
export const DentistWithPrincipal = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : DentistProfile,
});
export const AvailabilitySlot = IDL.Record({
  'dateTimeLabel' : IDL.Text,
  'slotId' : IDL.Nat,
  'isBooked' : IDL.Bool,
  'dentistId' : IDL.Principal,
});
export const FeedbackEntry = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const Testimonial = IDL.Record({
  'testimonialId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAvailabilitySlot' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookSlot' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
  'completeBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'declineBooking' : IDL.Func([IDL.Nat], [], []),
  'deleteUserScans' : IDL.Func([], [], []),
  'getAllDentists' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
  'getBookingMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getCallerLatestScan' : IDL.Func([], [IDL.Opt(ScanResult)], ['query']),
  'getCallerScanHistory' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDentistBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getDentistByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DentistWithPrincipal)],
      ['query'],
    ),
  'getDentistLanguages' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'getDentistProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DentistProfile)],
      ['query'],
    ),
  'getDentistSlots' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AvailabilitySlot)],
      ['query'],
    ),
  'getFeedbackList' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getPatientBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserScanHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ScanResult)],
      ['query'],
    ),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markPaymentPaid' : IDL.Func([IDL.Nat], [], []),
  'markPaymentReleased' : IDL.Func([IDL.Nat], [], []),
  'recordVisit' : IDL.Func([], [], []),
  'registerDentistProfile' : IDL.Func([DentistProfile], [], []),
  'removeAvailabilitySlot' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'submitFeedback' : IDL.Func([IDL.Text], [], []),
  'submitScan' : IDL.Func([ScanResult], [], []),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updateDentistProfile' : IDL.Func([DentistProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DentistProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'specialty' : IDL.Text,
    'isVerified' : IDL.Bool,
    'licenseNumber' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'bookingId' : IDL.Nat,
    'messageId' : IDL.Nat,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const ToothStatus = IDL.Variant({
    'risk' : IDL.Null,
    'healthy' : IDL.Null,
    'cavity' : IDL.Null,
  });
  const ToothRecord = IDL.Record({
    'status' : ToothStatus,
    'number' : IDL.Nat,
    'recommendation' : IDL.Text,
    'condition' : IDL.Text,
  });
  const ScanResult = IDL.Record({
    'teeth' : IDL.Vec(ToothRecord),
    'overallScore' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
    'declined' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'released' : IDL.Null,
  });
  const Booking = IDL.Record({
    'status' : BookingStatus,
    'paymentStatus' : PaymentStatus,
    'bookingId' : IDL.Nat,
    'patientId' : IDL.Principal,
    'createdAt' : Time,
    'slotId' : IDL.Nat,
    'dentistId' : IDL.Principal,
  });
  const DentistWithPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : DentistProfile,
  });
  const AvailabilitySlot = IDL.Record({
    'dateTimeLabel' : IDL.Text,
    'slotId' : IDL.Nat,
    'isBooked' : IDL.Bool,
    'dentistId' : IDL.Principal,
  });
  const FeedbackEntry = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const Testimonial = IDL.Record({
    'testimonialId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAvailabilitySlot' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookSlot' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
    'completeBooking' : IDL.Func([IDL.Nat], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat], [], []),
    'declineBooking' : IDL.Func([IDL.Nat], [], []),
    'deleteUserScans' : IDL.Func([], [], []),
    'getAllDentists' : IDL.Func([], [IDL.Vec(DentistProfile)], ['query']),
    'getBookingMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getCallerLatestScan' : IDL.Func([], [IDL.Opt(ScanResult)], ['query']),
    'getCallerScanHistory' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDentistBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getDentistByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DentistWithPrincipal)],
        ['query'],
      ),
    'getDentistLanguages' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getDentistProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DentistProfile)],
        ['query'],
      ),
    'getDentistSlots' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AvailabilitySlot)],
        ['query'],
      ),
    'getFeedbackList' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getPatientBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserScanHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ScanResult)],
        ['query'],
      ),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markPaymentPaid' : IDL.Func([IDL.Nat], [], []),
    'markPaymentReleased' : IDL.Func([IDL.Nat], [], []),
    'recordVisit' : IDL.Func([], [], []),
    'registerDentistProfile' : IDL.Func([DentistProfile], [], []),
    'removeAvailabilitySlot' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'submitFeedback' : IDL.Func([IDL.Text], [], []),
    'submitScan' : IDL.Func([ScanResult], [], []),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updateDentistProfile' : IDL.Func([DentistProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };